### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ksv1986** [ksv1986/foo_vis_projectm_ng#1]
- [ ] Update to foobar2000 2.x SDK
- [ ] Add x64 build
- [ ] Update projectM to 4.x
- [ ] Auto download projectM presets
